import React, {useEffect, useState} from 'react';
import {createRoot} from 'react-dom/client';
import './style.css';

type Data = Record<string, any>;
type Page = 'ranking'|'stock'|'universe'|'backtest'|'reports'|'health';
const pages: {id:Page;label:string;icon:string}[] = [{id:'ranking',label:'Tổng quan & xếp hạng',icon:'◈'},{id:'stock',label:'Chi tiết cổ phiếu',icon:'⌁'},{id:'universe',label:'Danh mục nghiên cứu',icon:'▦'},{id:'backtest',label:'Kiểm định chiến lược',icon:'↗'},{id:'reports',label:'Báo cáo PDF',icon:'▤'},{id:'health',label:'Chất lượng dữ liệu',icon:'◎'}];
const number = (value:any, digits=2) => value === null || value === undefined || !Number.isFinite(Number(value)) ? '—' : Number(value).toLocaleString('vi-VN',{maximumFractionDigits:digits});
async function api(path:string, method='GET', body?:Data):Promise<Data> {
  const response = await fetch(`/api${path}`, {method,headers:{'Content-Type':'application/json'},body:body ? JSON.stringify(body):undefined});
  const data = await response.json().catch(()=>({detail:'Máy chủ trả về dữ liệu không hợp lệ.'}));
  if(!response.ok) throw new Error(typeof data.detail==='string' ? data.detail : JSON.stringify(data.detail || data));
  return data;
}
function Empty({children}:{children:React.ReactNode}) {return <div className="empty"><span>◎</span><p>{children}</p></div>}
function Details({data}:{data:any}) {return <pre className="detail-json">{JSON.stringify(data,null,2)}</pre>}
function Chart({rows, valueKey='close'}:{rows:Data[];valueKey?:string}) {
  const values=rows.map(r=>Number(r[valueKey])).filter(v=>Number.isFinite(v));
  if(values.length<2) return <Empty>Chưa có đủ dữ liệu thật để hiển thị biểu đồ.</Empty>;
  const min=Math.min(...values),max=Math.max(...values),range=max-min||1;
  const points=values.map((v,i)=>`${20+i/(values.length-1)*760},${190-(v-min)/range*150}`).join(' ');
  return <div className="chart"><div className="chart-label"><span>{number(max)} <small>cao nhất</small></span><span>{number(min)} <small>thấp nhất</small></span></div><svg role="img" aria-label="Biểu đồ dữ liệu lịch sử thực tế" viewBox="0 0 800 220"><defs><linearGradient id="area" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="#2ec5a0" stopOpacity=".25"/><stop offset="100%" stopColor="#2ec5a0" stopOpacity="0"/></linearGradient></defs>{[40,90,140,190].map(y=><line key={y} x1="20" x2="780" y1={y} y2={y} stroke="#e9edf0"/>)}<polygon points={`20,210 ${points} 780,210`} fill="url(#area)"/><polyline points={points} fill="none" stroke="#189c7b" strokeWidth="3"/></svg><div className="chart-label"><small>{String(rows[0]?.date||rows[0]?.time||'Bắt đầu')}</small><small>{String(rows.at(-1)?.date||rows.at(-1)?.time||'Kết thúc')}</small></div></div>
}
function App(){
  const [page,setPage]=useState<Page>('ranking'); const [health,setHealth]=useState<Data>({}); const [ranking,setRanking]=useState<Data>({}); const [universe,setUniverse]=useState<Data>({}); const [selection,setSelection]=useState<string[]>([]); const [symbol,setSymbol]=useState('FPT'); const [stock,setStock]=useState<Data|null>(null); const [reports,setReports]=useState<Data[]>([]); const [quality,setQuality]=useState<Data>({}); const [backtest,setBacktest]=useState<Data|null>(null);
  const [busy,setBusy]=useState(false); const [loading,setLoading]=useState(true); const [message,setMessage]=useState(''); const [error,setError]=useState(''); const [startDate,setStartDate]=useState('2023-01-01'); const [endDate,setEndDate]=useState(new Date().toLocaleDateString('en-CA',{timeZone:'Asia/Ho_Chi_Minh'})); const [mode,setMode]=useState('S_ex_news'); const [topN,setTopN]=useState(3);
  const entries:Data[]=[...(ranking.main_ranking||[]),...(ranking.secondary_ranking||[])]; const ranked:Data[]=ranking.main_ranking||[];
  async function load(){
    setLoading(true); setError('');
    const results=await Promise.allSettled([api('/health'),api('/ranking'),api('/universe'),api('/reports'),api('/data/quality')]);
    const setters=[setHealth,setRanking,(d:Data)=>{setUniverse(d);setSelection((d.selected||[]).map((s:Data)=>s.symbol))},(d:Data)=>setReports(d.reports||[]),setQuality];
    results.forEach((r,i)=>{if(r.status==='fulfilled')setters[i](r.value);else setError(r.reason.message||'Không kết nối được API. Hãy khởi động backend ở cổng 8000.');}); setLoading(false);
  }
  useEffect(()=>{void load()},[]);
  useEffect(()=>{if(page!=='stock')return;let live=true;setStock(null);setError('');api(`/stocks/${encodeURIComponent(symbol)}`).then(d=>{if(live)setStock(d)}).catch(e=>{if(live)setError(e.message)});return()=>{live=false}},[page,symbol]);
  async function poll(id:string){for(let i=0;i<300;i++){const job=await api(`/jobs/${id}`);if(job.status==='failed')throw new Error(job.error||'Tác vụ thất bại.');if(job.status==='completed')return job;await new Promise(r=>setTimeout(r,1000))}throw new Error('Tác vụ vẫn đang xử lý. Bạn có thể tải lại trang để kiểm tra.');}
  async function action(path:string,body?:Data){setBusy(true);setError('');setMessage('Đang thực hiện yêu cầu…');try{const result=await api(path,'POST',body);if(result.job_id||result.report_id){setMessage('Đang xử lý dữ liệu từ nguồn. Vui lòng giữ trang mở…');const job=await poll(result.job_id||result.report_id);if(path==='/backtest/run')setBacktest(job.result||job);if(result.report_id)setMessage('Báo cáo đã sẵn sàng. Tải xuống trong danh sách bên dưới.');else setMessage('Đã hoàn tất tác vụ.');}else setMessage('Đã lưu danh mục nghiên cứu.');await load()}catch(e){setError(e instanceof Error?e.message:String(e));setMessage('')}finally{setBusy(false)}}
  function openStock(s:string){setSymbol(s);setPage('stock')}
  const title=pages.find(p=>p.id===page)?.label;
  return <div className="app"><aside className="sidebar"><a className="brand" href="#" onClick={e=>{e.preventDefault();setPage('ranking')}}><span className="brand-icon">V</span><span>VN30<span className="brand-sub">INVESTMENT RESEARCH</span></span></a><div className="nav-label">KHÔNG GIAN PHÂN TÍCH</div><nav>{pages.map(p=><button key={p.id} className={`nav-item ${page===p.id?'active':''}`} onClick={()=>setPage(p.id)}><span>{p.icon}</span>{p.label}{page===p.id&&<i/>}</button>)}</nav><div className="sidebar-bottom"><div className="source-dot"/><div><b>Nguồn dữ liệu Vnstock</b><small>Dữ liệu thật · Phương pháp minh bạch</small></div></div></aside><main><header className="topbar"><div className="breadcrumb">Không gian nghiên cứu <span>/</span> <b>{title}</b></div><div className="connection"><i className={health.status?'online':''}/>{health.status?'API đã kết nối':'Chưa kết nối API'}</div></header><div className="content"><div className="page-head"><div><div className="eyebrow">VIETNAM EQUITY RESEARCH</div><h1>{title}</h1><p>Phân tích cơ bản, kỹ thuật và tin tức trong một không gian.</p></div><div className="actions"><button className="button ghost" disabled={busy||loading} onClick={()=>void load()}>↻ Tải lại</button><button className="button primary" disabled={busy||loading} onClick={()=>void action('/analysis/run')}>{busy?'Đang xử lý…':'✦ Chạy phân tích'}</button></div></div>
    {error&&<div role="alert" className="notice error">{error}</div>}{message&&<div role="status" className="notice">{message}</div>}{loading&&<div className="notice">Đang kết nối và đọc dữ liệu…</div>}
    {page==='ranking'&&<><div className="stats"><div className="stat"><span>DANH MỤC NGHIÊN CỨU</span><b>{universe.selected?.length??'—'} <small>cổ phiếu</small></b><p>Từ danh sách VN30</p></div><div className="stat"><span>ĐỦ ĐIỀU KIỆN XẾP HẠNG</span><b>{ranked.length}<small> / {entries.length}</small></b><p>Được kiểm tra chất lượng dữ liệu</p></div><div className="stat"><span>ĐIỂM DẪN ĐẦU</span><b className="green">{number(ranked[0]?.total_score)}<small> / 100</small></b><p>{ranked[0]?.symbol||'Chưa có kết quả phân tích'}</p></div><div className="stat"><span>NGÀY PHÂN TÍCH</span><b className="date">{ranking.as_of_date||'—'}</b><p>Phiên bản {ranking.scoring_version||'—'}</p></div></div><section className="panel"><div className="panel-head"><div><h2>Xếp hạng cơ hội nghiên cứu</h2><p>FA · Phân tích cơ bản &nbsp; TA · Phân tích kỹ thuật &nbsp; NEWS · Tin tức</p></div><span className="badge">{entries.length} MÃ</span></div>{entries.length?<div className="table-wrap"><table><thead><tr><th>HẠNG</th><th>CỔ PHIẾU</th><th>NGÀNH</th><th>FA</th><th>TA</th><th>NEWS</th><th>TỔNG ĐIỂM</th><th>TRẠNG THÁI</th></tr></thead><tbody>{entries.map((s,i)=><tr key={s.symbol} onClick={()=>openStock(s.symbol)} tabIndex={0} onKeyDown={e=>{if(e.key==='Enter')openStock(s.symbol)}}><td><span className={`rank ${i<3?'top':''}`}>{s.rank||'—'}</span></td><td><b className="ticker">{s.symbol}</b><small className="row-link">Xem phân tích ↗</small></td><td>{s.sector}</td><td>{number(s.fa_score)}</td><td>{number(s.ta_score)}</td><td>{number(s.news_score)}</td><td><div className="score-cell"><b>{number(s.total_score)}</b><div className="score-track"><i style={{width:`${Math.min(100,Math.max(0,s.total_score||0))}%`}}/></div></div></td><td><span className={`badge ${ranked.includes(s)?'success':'warning'}`}>{s.status}</span>{s.reasons?.length>0&&<small className="reasons">{s.reasons.join('; ')}</small>}</td></tr>)}</tbody></table></div>:<Empty>Chưa có kết quả xếp hạng. Chọn danh mục nghiên cứu, sau đó nhấn “Chạy phân tích”.</Empty>}</section><div className="method"><span>◈</span><div><b>Một góc nhìn có thể kiểm chứng</b><p>Điểm số được tính từ dữ liệu nguồn và cấu hình công khai. Thiếu dữ liệu sẽ được ghi nhận trong trạng thái cổ phiếu.</p></div><button className="text-button" onClick={()=>setPage('health')}>Kiểm tra dữ liệu →</button></div></>}
    {page==='universe'&&<section className="panel"><div className="panel-head"><div><h2>Lựa chọn từ 5 đến 10 cổ phiếu</h2><p>Danh sách thành viên được lấy trực tiếp từ nguồn Vnstock.</p></div><span className="badge">ĐÃ CHỌN {selection.length}/10</span></div>{(universe.warnings||[]).map((w:string)=><div className="notice" key={w}>{w}</div>)}<div className="universe-grid">{(universe.vn30_members||[]).map((s:string)=><button key={s} className={`stock-chip ${selection.includes(s)?'selected':''}`} disabled={!selection.includes(s)&&selection.length>=10} onClick={()=>setSelection(selection.includes(s)?selection.filter(x=>x!==s):[...selection,s])}><span>{s}</span><span>{selection.includes(s)?'✓':'+'}</span></button>)}</div>{!universe.vn30_members?.length&&<Empty>Chưa xác minh được danh sách VN30 từ nguồn. Hãy kiểm tra kết nối trước khi thay đổi danh mục.</Empty>}<div className="panel-footer"><span>{selection.join(' · ')||'Chưa chọn cổ phiếu'}</span><button className="button primary" disabled={busy||selection.length<5||selection.length>10||!universe.vn30_members?.length} onClick={()=>void action('/universe/select',{symbols:selection})}>Lưu danh mục</button></div></section>}
    {page==='stock'&&<><div className="panel stock-selector"><label htmlFor="symbol">Cổ phiếu</label><select id="symbol" value={symbol} onChange={e=>setSymbol(e.target.value)}>{[...new Set([symbol,...(universe.selected||[]).map((s:Data)=>s.symbol),...entries.map(s=>s.symbol)])].map(s=><option key={s}>{s}</option>)}</select><button disabled={busy||!stock} className="button ghost" onClick={()=>void action(`/reports/stock/${symbol}`)}>Xuất báo cáo PDF</button></div>{stock?<><section className="panel"><div className="panel-head"><div><h2>{stock.symbol} <span className="muted">{stock.name||stock.sector}</span></h2><p>Lịch sử giá từ nguồn thực tế. Đơn vị theo dữ liệu nguồn.</p></div><span className="badge">{stock.prices?.length||0} PHIÊN</span></div><Chart rows={stock.prices||[]}/></section><div className="two-col">{[{label:'Phân tích cơ bản',value:stock.fundamentals},{label:'Phân tích kỹ thuật',value:stock.indicators},{label:'Điểm và giải thích',value:stock.breakdown},{label:'Tin tức',value:stock.news}].map(s=><section className="panel" key={s.label}><div className="panel-head"><h2>{s.label}</h2></div><Details data={s.value}/></section>)}</div></>:<Empty>Chưa có phân tích cho {symbol}. Hãy chạy phân tích danh mục trước.</Empty>}</>}
    {page==='backtest'&&<><section className="panel"><div className="panel-head"><div><h2>Kiểm định với dữ liệu lịch sử</h2><p>Phí giao dịch, thuế, trượt giá và dữ liệu thiếu được xử lý theo cấu hình.</p></div></div><form className="form-grid" onSubmit={e=>{e.preventDefault();void action('/backtest/run',{start_date:startDate,end_date:endDate,mode,top_n:topN,rebalance:'monthly'})}}><label>Từ ngày<input type="date" value={startDate} onChange={e=>setStartDate(e.target.value)} required/></label><label>Đến ngày<input type="date" value={endDate} onChange={e=>setEndDate(e.target.value)} min={startDate} required/></label><label>Chế độ<select value={mode} onChange={e=>setMode(e.target.value)}><option value="S_ex_news">FA + TA (không tin tức)</option><option value="S_full">FA + TA + NEWS</option></select></label><label>Số mã nắm giữ<input type="number" min="1" max={selection.length||10} value={topN} onChange={e=>setTopN(Number(e.target.value))}/></label><button className="button primary" disabled={busy}>Chạy backtest</button></form></section>{backtest?<><section className="panel"><div className="panel-head"><h2>Kết quả kiểm định</h2><span className="badge">{backtest.status||'Hoàn tất'}</span></div>{(backtest.limitations||[]).map((v:string)=><div className="notice" key={v}>{v}</div>)}<Details data={backtest.metrics||backtest}/>{backtest.equity_curve?.length>0&&<Chart rows={backtest.equity_curve} valueKey={'equity' in backtest.equity_curve[0]?'equity':'portfolio_value'}/>}</section>{backtest.trades?.length>0&&<details className="panel"><summary>Lịch sử giao dịch ({backtest.trades.length})</summary><Details data={backtest.trades}/></details>}</>:<Empty>Chưa chạy kiểm định. Kết quả chỉ xuất hiện khi dữ liệu lịch sử đáp ứng yêu cầu.</Empty>}</>}
    {page==='reports'&&<section className="panel"><div className="panel-head"><div><h2>Thư viện báo cáo</h2><p>Xuất kết quả nghiên cứu thành PDF để lưu trữ và đối chiếu.</p></div><button className="button primary" disabled={busy||!entries.length} onClick={()=>void action('/reports/summary')}>+ Báo cáo tổng hợp</button></div>{reports.length?<div className="table-wrap"><table><thead><tr><th>BÁO CÁO</th><th>LOẠI</th><th>TRẠNG THÁI</th><th>TẢI XUỐNG</th></tr></thead><tbody>{reports.map(r=><tr key={r.report_id}><td>{r.report_id.slice(0,8)}</td><td>{r.kind==='summary_report'?'Tổng hợp danh mục':'Chi tiết cổ phiếu'}</td><td>{r.status}</td><td>{r.status==='completed'?<a className="download" href={r.download_url||`/api/reports/${r.report_id}/download`} download>Tải PDF ↓</a>:<span className="muted">{r.status==='failed'?'Tạo báo cáo thất bại':'Đang tạo…'}</span>}</td></tr>)}</tbody></table></div>:<Empty>Chưa có báo cáo. Chạy phân tích rồi tạo báo cáo tổng hợp hoặc báo cáo cổ phiếu.</Empty>}</section>}
    {page==='health'&&<><section className="panel"><div className="panel-head"><div><h2>Trạng thái hệ thống</h2><p>Cấu hình chấm điểm và tình trạng kết nối hiện tại.</p></div><button className="button ghost" disabled={busy} onClick={()=>void action('/data/refresh')}>↻ Làm mới dữ liệu</button></div><Details data={health}/></section><section className="panel"><div className="panel-head"><div><h2>Kiểm tra chất lượng nguồn</h2><p>Đọc kết quả xác minh nguồn trước khi sử dụng kết quả nghiên cứu.</p></div></div><Details data={quality}/></section></>}
    <footer><span>{ranking.disclaimer||'Hệ thống phục vụ nghiên cứu và học tập; kết quả không phải khuyến nghị đầu tư.'}</span><b>VN30 / RESEARCH</b></footer></div></main></div>
}
createRoot(document.getElementById('root')!).render(<React.StrictMode><App/></React.StrictMode>);
